-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 05:36:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crud_mysql_test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `crud_mysql_test` ;

-- -----------------------------------------------------
-- Schema crud_mysql_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crud_mysql_test` DEFAULT CHARACTER SET utf8 ;
USE `crud_mysql_test` ;

-- -----------------------------------------------------
-- Table `crud_mysql_test`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_mysql_test`.`task` (
  `id` INT(7) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL DEFAULT '',
  `description` VARCHAR(250) NOT NULL DEFAULT '',
  `done` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1000000;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
